language: python
cache: pip
dist: xenial
matrix:
    fast_finish: true
    include:

      - { python: "3.5", env: DJANGO=1.11 }
      - { python: "3.5", env: DJANGO=2.0 }
      - { python: "3.5", env: DJANGO=2.1 }
      - { python: "3.5", env: DJANGO=2.2 }

      - { python: "3.6", env: DJANGO=1.11 }
      - { python: "3.6", env: DJANGO=2.0 }
      - { python: "3.6", env: DJANGO=2.1 }
      - { python: "3.6", env: DJANGO=2.2 }
      - { python: "3.6", env: DJANGO=3.0 }
      - { python: "3.6", env: DJANGO=master }

      - { python: "3.7", env: DJANGO=2.0 }
      - { python: "3.7", env: DJANGO=2.1 }
      - { python: "3.7", env: DJANGO=2.2 }
      - { python: "3.7", env: DJANGO=3.0 }
      - { python: "3.7", env: DJANGO=master }

      - { python: "3.8", env: DJANGO=3.0 }
      - { python: "3.8", env: DJANGO=master }

      - { python: "3.8", env: TOXENV=base }
      - { python: "3.8", env: TOXENV=lint }
      - { python: "3.8", env: TOXENV=docs }

      - python: "3.8"
        env: TOXENV=dist
        script:
          - python setup.py bdist_wheel
          - rm -r djangorestframework.egg-info  # see #6139
          - tox --installpkg ./dist/djangorestframework-*.whl
          - tox  # test sdist

      - python: "3.7"
        env: DOCS=links
        script:
          - pip install -r requirements/requirements-documentation.txt
          - mkdocs serve &
          - WAIT_TIME=0 && until nc -vzw 2 localhost 8000 || [ $WAIT_TIME -eq 5 ]; do sleep $(( WAIT_TIME++ )); done
          - if [ $WAIT_TIME == 5 ]; then echo cannot start mkdocs server on http://localhost:8000; exit 1; fi
          - pylinkvalidate.py -P http://localhost:8000/

    allow_failures:
      - env: DJANGO=master
      - env: DOCS=links 

install:
    - pip install tox tox-venv tox-travis

script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV,DJANGO

notifications:
    email: false
